import { expect, test } from '@playwright/test'

test('loads a living world and exposes simulation controls', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByText('EvoTerrarium')).toBeVisible()
  await expect(page.getByRole('application', { name: 'Interactive evolving ecosystem' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Pause simulation' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Add grazer' })).toBeVisible()
  await expect(page.getByText('FOOD WEB')).toBeVisible()
})

test('creates a deterministic world from a chosen seed', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Create a new world' }).click()
  await page.getByLabel('WORLD SEED').fill('E2E-2244')
  await page.getByRole('button', { name: 'Grow this world' }).click()
  await expect(page.getByText('A living world awakens')).toBeVisible()
})

test('pauses while the new-world dialog is open and restores the prior speed', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Run at 20 times speed' }).click()
  await page.getByRole('button', { name: 'Create a new world' }).click()
  await expect(page.getByText('World paused while choosing.')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Pause simulation' })).toHaveClass(/active/)
  await page.getByRole('button', { name: 'Close' }).click()
  await expect(page.getByRole('button', { name: 'Run at 20 times speed' })).toHaveClass(/active/)
})

test('keeps drag for exploration while a creation tool is armed', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Run at 20 times speed' }).click()
  await page.getByRole('button', { name: 'Water' }).click()
  await expect(page.getByText('WORLD PAUSED · CREATION TOOL')).toBeVisible()
  await expect(page.getByText('Tap to apply · Drag to explore · Esc to finish')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Pause simulation' })).toHaveClass(/active/)
  await page.keyboard.press('Escape')
  await expect(page.getByText('WORLD PAUSED · CREATION TOOL')).toBeHidden()
  await expect(page.getByRole('button', { name: 'Run at 20 times speed' })).toHaveClass(/active/)
})

test('opens the latest living genealogy from world statistics', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Run at 20 times speed' }).click()
  await expect(page.getByRole('button', { name: 'Browse latest lineage' })).toBeEnabled()
  await page.getByRole('button', { name: 'Browse latest lineage' }).click()
  await expect(page.getByRole('complementary', { name: /Genealogy of/ })).toBeVisible()
  await expect(page.getByText(/WORLD PAUSED · GENEALOGY/)).toBeVisible()
  await expect(page.getByRole('button', { name: 'Pause simulation' })).toHaveClass(/active/)
  await expect(page.getByRole('heading', { name: 'Family line' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Inherited change' })).toBeVisible()
  await page.getByRole('button', { name: 'Close genealogy' }).click()
  await expect(page.getByRole('button', { name: 'Run at 20 times speed' })).toHaveClass(/active/)
})

test('opens the species codex, pauses the world and restores speed', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Run at 20 times speed' }).click()
  await expect(page.getByRole('button', { name: 'Open species codex' })).toBeEnabled()
  await page.getByRole('button', { name: 'Open species codex' }).click()
  await expect(page.getByRole('complementary', { name: 'Species codex' })).toBeVisible()
  await expect(page.getByText('WORLD PAUSED · SPECIES CODEX')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Pause simulation' })).toHaveClass(/active/)
  await expect(page.getByRole('heading', { name: 'Selection evidence' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Genetic signature' })).toBeVisible()
  await page.getByRole('button', { name: 'Close species codex' }).click()
  await expect(page.getByRole('button', { name: 'Run at 20 times speed' })).toHaveClass(/active/)
})

test('opens the climate lab and arms a bounded regional pressure', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Run at 20 times speed' }).click()
  await page.getByRole('button', { name: 'Open climate lab' }).click()
  await expect(page.getByRole('complementary', { name: 'Climate and disaster lab' })).toBeVisible()
  await expect(page.getByText('LIVE ENVIRONMENT')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Run at 20 times speed' })).toHaveClass(/active/)
  await page.getByRole('button', { name: /Wildfire/ }).click()
  await expect(page.getByText('WORLD PAUSED · REGIONAL PRESSURE')).toBeVisible()
  await expect(page.getByText('Tap to apply · Drag to explore · Esc to finish')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Pause simulation' })).toHaveClass(/active/)
  await page.keyboard.press('Escape')
  await expect(page.getByRole('button', { name: 'Run at 20 times speed' })).toHaveClass(/active/)
})

test('keeps the optional Social Lab live while exposing group rules', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Run at 20 times speed' }).click()
  await page.getByRole('button', { name: 'Toggle Social Lab' }).click()
  await expect(page.getByRole('complementary', { name: 'Social behaviour lab' })).toBeVisible()
  await expect(page.getByText('OPTIONAL DEBUG VIEW')).toBeVisible()
  await expect(page.getByText('Local rules, live—not scripted paths')).toBeVisible()
  await expect(page.getByText('LIVE GROUPS')).toBeVisible()
  await expect(page.getByText('MIGRATION EVIDENCE')).toBeVisible()
  await expect(page.getByText('SELECTED MEMORY')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Run at 20 times speed' })).toHaveClass(/active/)
  await page.getByRole('button', { name: 'Close Social Lab' }).click()
  await expect(page.getByRole('complementary', { name: 'Social behaviour lab' })).toBeHidden()
})

test('names a save slot and replays an ecological landmark from the archive', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Run at 20 times speed' }).click()
  await page.getByRole('button', { name: 'Open World Archive' }).click()
  await expect(page.getByRole('complementary', { name: 'World archive' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Pause simulation' })).toHaveClass(/active/)

  await page.getByLabel('Save name').fill('E2E field notes')
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(page.getByText('Saved “E2E field notes”.')).toBeVisible()
  await expect(page.getByText('E2E field notes')).toBeVisible()

  await page.getByRole('button', { name: 'Replay', exact: true }).click()
  await page.getByRole('button', { name: /A living world awakens/ }).click()
  await expect(page.getByText('Replay rebuilt at tick 0.')).toBeVisible()
  await page.getByRole('button', { name: 'Return live' }).click()
  await expect(page.getByText('Returned to the live world.')).toBeVisible()

  await page.getByRole('button', { name: 'Close', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Run at 20 times speed' })).toHaveClass(/active/)
})

test('exposes validated world portability and reproducible seed sharing', async ({ page }) => {
  await page.goto('/?seed=SHARE-6204')
  await page.getByRole('button', { name: 'Open World Archive' }).click()
  await page.getByRole('button', { name: 'Share', exact: true }).click()
  await expect(page.getByText('SHARE-6204')).toBeVisible()
  await expect(page.getByText('Portable world record')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Copy seed link' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Export JSON' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Import JSON' })).toBeVisible()
})
